In [ ]:
# Numpy Array Operations

In [ ]:
import numpy as np

In [ ]:
# 1. Create a 1D NumPy Array:?

temperatures_w1= np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)


[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#2. Inspection and Properties?

print("shape :",temperatures_w1.shape)

print("Number of Elements:",temperatures_w1.size)

print("Data Type:",temperatures_w1.dtype)

shape : (7,)
Number of Elements: 7
Data Type: float64


In [ ]:
# 3. Array Operations:

""" ● Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32"""

temperatures_w1_F = (temperatures_w1 * 9/5) + 32
print(temperatures_w1_F)


[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
# ● Find the maximum, minimum, and mean temperatures for the week.?

print("Maximum Temperature:",np.max(temperatures_w1))
print("Minimum Temperature:",np.min(temperatures_w1))
print("Mean Temperature:",np.mean(temperatures_w1))


Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [ ]:
# Array slicing and indexing:

In [ ]:
# 1 Extract the temperatures for the first three days of the week.?

print("First 3 days :",temperatures_w1[:3])


First 3 days : [22.5 25.3 20.8]


In [ ]:
# Extract the temperatures for the weekend (last two days).?

print("Weekend :",temperatures_w1[-2:])

Weekend : [24.8 21.9]


In [ ]:
# Extract the temperatures for the middle three days of the week.?

print("Middle 3 days :",temperatures_w1[2:5])

Middle 3 days : [20.8 23.4 26.1]


In [ ]:
# CREATE A 2D ARRAY

In [ ]:
temperatures=np.array([
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  #week1
[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   #week2
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
# Inspect and Slice the 2D Array:

In [ ]:
"""Inspect and print the shape, data type, and total number of elements in the
temperatures array. ?"""

print("Shape:",temperatures.shape)
print("Data Type:",temperatures.dtype)
print("Total Elements:",temperatures.size)


Shape: (2, 7)
Data Type: float64
Total Elements: 14


In [ ]:
""" Extract the temperatures for each week and the weekends (last two days)
for both weeks."""

print("week1:",temperatures[0])
print("week2:",temperatures[1])
print("week1 weekend:",temperatures[0][-2:])
print("week2 weekend:",temperatures[1][-2:])


week1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
week2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
week1 weekend: [24.8 21.9]
week2 weekend: [22.8 20.1]


In [ ]:
# PANDAS SERIES.

import pandas as pd

In [ ]:

Marks=pd.Series([95,92,89,85,80],
                index=['Rank1','Rank2','Rank3','Rank4','Rank5'])
print(Marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
# 1. INDEXING AND SLICING

In [ ]:
# Use the integer index position to access the mark of the 1st rank student. ?

print('First Rank Student:',Marks[0])


First Rank Student: 95


In [ ]:
"""Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels."""

print("Top 3 Ranks:",Marks.loc[['Rank1','Rank2','Rank3']])


Top 3 Ranks: Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
#Use the iloc accessor to retrieve the mark of the 3rd rank student.?

print("Thired Rank Student:",Marks.iloc[2])


Thired Rank Student: 89


In [ ]:
"""Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90. """

print("Marks greater than 90:",Marks[Marks>90])


Marks greater than 90: Rank1    95
Rank2    92
dtype: int64


In [ ]:
# MANIPULATING SERIES

In [ ]:
#Modify the mark of the student with the 1st rank to 100.  ?

Marks['Rank1']=100
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
#Remove the entry corresponding to the last rank from the Series.?

Marks=Marks.drop('Rank5')
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
#Compute the CGPA by dividing each mark in the Series by 10. ?

CGPA=Marks/10
print(CGPA)


Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
# PANDAS DATAFRAME

In [ ]:
transaction=pd.DataFrame({
    "TransactionID":[101,102,103,104,105,106,107,108,109,110],
    'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics' ],
    ' Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North' ],
    'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transaction)

   TransactionID ProductCategory  Region  Amount
0            101     Electronics   North     200
1            102        Clothing   South     150
2            103     Electronics   North     300
3            104       Furniture    East     450
4            105        Clothing    West     200
5            106     Electronics   North     250
6            107       Furniture    East     300
7            108        Clothing    West     180
8            109       Furniture   South     350
9            110     Electronics   North     400


In [ ]:
"""Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types. """

In [ ]:
#head

print(transaction.head())

   TransactionID ProductCategory  Region  Amount
0            101     Electronics   North     200
1            102        Clothing   South     150
2            103     Electronics   North     300
3            104       Furniture    East     450
4            105        Clothing    West     200


In [ ]:
#tail

print(transaction.tail())

   TransactionID ProductCategory  Region  Amount
5            106     Electronics   North     250
6            107       Furniture    East     300
7            108        Clothing    West     180
8            109       Furniture   South     350
9            110     Electronics   North     400


In [ ]:
#shape,column,dtype

print(transaction.shape)
print(transaction.columns)
print(transaction.dtypes)

(10, 4)
Index(['TransactionID', 'ProductCategory', ' Region', 'Amount'], dtype='object')
TransactionID       int64
ProductCategory    object
 Region            object
Amount              int64
dtype: object


In [ ]:
#Display only the 'ProductCategory' and 'Amount' columns. ?

print(transaction[['ProductCategory','Amount']])


  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
#Retrieve the last 3 columns of the DataFrame using iloc or loc?

print(transaction.iloc[:,-3:])

  ProductCategory  Region  Amount
0     Electronics   North     200
1        Clothing   South     150
2     Electronics   North     300
3       Furniture    East     450
4        Clothing    West     200
5     Electronics   North     250
6       Furniture    East     300
7        Clothing    West     180
8       Furniture   South     350
9     Electronics   North     400


In [ ]:
#Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200?

print(transaction[(transaction['Region']=='North') &
 (transaction['Amount']>200)])


   TransactionID ProductCategory  Region  Amount
2            103     Electronics   North     300
5            106     Electronics   North     250
9            110     Electronics   North     400


In [ ]:
#Find the value counts for the 'ProductCategory' column?

print(transaction['ProductCategory'].value_counts())


ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
#Find the unique values in the 'Region' column.?

print(transaction[' Region'].unique())


['North' 'South' 'East' 'West']


In [ ]:
#Group by 'Region' and find the mean amount for each region.?

print(transaction.groupby(' Region')['Amount'].mean())


 Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
# MANIPULATING THE DATAFRAME

In [ ]:
#Modify the 'Amount' for the transaction with TransactionID 102 to 165?

transaction.loc[transaction['TransactionID']==102,'Amount']=165
print(transaction)


   TransactionID ProductCategory  Region  Amount
0            101     Electronics   North     200
1            102        Clothing   South     165
2            103     Electronics   North     300
3            104       Furniture    East     450
4            105        Clothing    West     200
5            106     Electronics   North     250
6            107       Furniture    East     300
7            108        Clothing    West     180
8            109       Furniture   South     350
9            110     Electronics   North     400


In [ ]:
#Add a new column 'Discount' by calculating 10% of the 'Amount'.?

transaction['Discount']=transaction['Amount']*0.1
print(transaction)


   TransactionID ProductCategory  Region  Amount  Discount
0            101     Electronics   North     200      20.0
1            102        Clothing   South     165      16.5
2            103     Electronics   North     300      30.0
3            104       Furniture    East     450      45.0
4            105        Clothing    West     200      20.0
5            106     Electronics   North     250      25.0
6            107       Furniture    East     300      30.0
7            108        Clothing    West     180      18.0
8            109       Furniture   South     350      35.0
9            110     Electronics   North     400      40.0


In [ ]:
#Remove the row with TransactionID 109.?

transaction = transaction[transaction['TransactionID'] != 109]
print(transaction)


   TransactionID ProductCategory  Region  Amount  Discount
0            101     Electronics   North     200      20.0
1            102        Clothing   South     165      16.5
2            103     Electronics   North     300      30.0
3            104       Furniture    East     450      45.0
4            105        Clothing    West     200      20.0
5            106     Electronics   North     250      25.0
6            107       Furniture    East     300      30.0
7            108        Clothing    West     180      18.0
9            110     Electronics   North     400      40.0


In [ ]:
#Delete the 'Discount' column from the DataFrame?

transaction=transaction.drop(columns=['Discount'])
print(transaction)

   TransactionID ProductCategory  Region  Amount
0            101     Electronics   North     200
1            102        Clothing   South     165
2            103     Electronics   North     300
3            104       Furniture    East     450
4            105        Clothing    West     200
5            106     Electronics   North     250
6            107       Furniture    East     300
7            108        Clothing    West     180
9            110     Electronics   North     400
